dbt_cloud:
  outputs:
    dev:
      account: BWB47273
      database: analytics
      password: Sachin$123
      role: analyticsengineer
      schema: DBT_AMISHRA
      threads: 3
      type: snowflake
      user: sachin
      warehouse: TRANSFORM_WH
  target: dev


